pages.learn = {
    categories: [
        {
            name: 'Bagian 1: Fondasi Robotika',
            items: [
                {
                    id: 'modul01',
                    title: 'Pertemuan 1: Kontrak Kuliah dan Pengantar Robotika',
                    lines: [
                        '**Pertemuan 1: Kontrak Kuliah dan Pengantar Robotika**',
                        '*Robot bukan sekadar mesin — ia adalah jembatan antara dunia fisik dan dunia digital yang kita bangun.*',
                        '---',
                        'Pertemuan ini membuka perjalanan Anda di mata kuliah Robotika. Kita akan menyepakati kontrak kuliah, menelusuri RPS 16 pertemuan, dan memahami mengapa robotika menjadi salah satu bidang paling menarik di informatika modern.',
                        'Anda juga akan menyiapkan alat kerja utama: ESP32, lingkungan Arduino IDE, dan aplikasi web kontroler untuk proyek payung **RoboLab** — robot sumo berbasis WiFi.',
                        '---',
                        '### Mengapa Robotika Penting bagi Anda?',
                        'card:Robotika adalah Integrasi Ilmu:Robotika menggabungkan pemrograman, elektronik, mekanik, dan kecerdasan buatan. Ia adalah bidang yang menuntut pemahaman lintas disiplin.',
                        'card:Industri 4.0 Butuh Robotik:Otomasi pabrik, kendaraan otonom, drone, dan robot layanan adalah realitas industri modern. Menguasai robotika membuka peluang karier yang luas.',
                        'card:Robot Sumo adalah Laboratorium Sempurna:Robot sumo menggabungkan sensor, aktuator, kendali, dan strategi dalam satu proyek kecil. Ia adalah cara terbaik memahami robotika secara holistik.',
                        '---',
                        '### Peta Medan Robotika',
                        'Mata kuliah ini dibagi menjadi empat fase besar. Setiap fase membangun di atas fase sebelumnya, dan semuanya bermuara pada satu proyek payung: **RoboLab**.',
                        'table:[{"Fase": "Bagian 1", "Fokus": "Fondasi robotika", "Pertemuan": "P1–P4"}, {"Fase": "Bagian 2", "Fokus": "Sensor, aktuator, dan UTS", "Pertemuan": "P5–P8"}, {"Fase": "Bagian 3", "Fokus": "Kinematika, pemrograman, dan visi", "Pertemuan": "P9–P12"}, {"Fase": "Bagian 4", "Fokus": "Visi, perancangan, dan evaluasi akhir", "Pertemuan": "P13–P16"}]',
                        '---',
                        '### Visi Proyek RoboLab — Robot Sumo',
                        'RoboLab adalah robot sumo berbasis ESP32 yang dikendalikan melalui aplikasi web via WiFi. Anda akan membangun robot dari nol: mekanik, elektronik, firmware, dan antarmuka kontrol.',
                        '```javascript',
                        '// Arsitektur RoboLab (disederhanakan)\n// Aplikasi Web (HTML+CSS+JS)\n//   ↓ WebSocket / HTTP\n// ESP32 (WiFi)\n//   ↓ GPIO\n// Motor Driver → Motor DC\n//   ↑\n// Sensor (ultrasonik, inframerah, garis)\n\nconst ROBOLAB = {\n    nama: \'RoboLab\',\n    platform: \'ESP32\',\n    bahasa: [\'JavaScript\', \'HTML\', \'CSS\', \'Arduino (ino)\'],\n    koneksi: \'WiFi (WebSocket)\',\n    misi: \'Robot sumo otonom dan terkendali\'\n};\n\nconsole.log(\'Proyek:\', ROBOLAB.nama);\nconsole.log(\'Platform:\', ROBOLAB.platform);\nconsole.log(\'Koneksi:\', ROBOLAB.koneksi);',
                        '```',
                        '---',
                        '### Setup Alat Kerja',
                        'Sebelum pertemuan berikutnya, pastikan semua alat berikut sudah tersedia dan berfungsi. Robotika memerlukan kombinasi perangkat keras dan lunak.',
                        '```javascript',
                        '// Checklist setup lingkungan kerja\n// PERANGKAT KERAS:\n// 1. ESP32 development board\n// 2. Motor driver (L298N atau sejenis)\n// 3. 2 motor DC + roda\n// 4. Sensor ultrasonik HC-SR04\n// 5. Sensor inframerah (garis)\n// 6. Baterai LiPo 2S + regulator\n// 7. Kabel jumper dan breadboard\n\n// PERANGKAT LUNAK:\n// 1. Arduino IDE dengan board ESP32\n// 2. Editor kode (VS Code) untuk aplikasi web\n// 3. Browser modern dengan DevTools\n// 4. Akun GitHub aktif\n\n// Uji cepat: upload sketch kosong ke ESP32\n// dan pastikan Serial Monitor menampilkan pesan:\n\nvoid setup() {\n    Serial.begin(115200);\n    Serial.println("RoboLab siap!");\n}\nvoid loop() {\n    delay(1000);\n}',
                        '```',
                        '---',
                        '### 3 Konsep Inti Pertemuan Ini',
                        'card:Robotika adalah Integrasi:Robotika bukan hanya satu disiplin. Ia adalah integrasi pemrograman, elektronik, mekanik, dan kendali.',
                        'card:Robot Sumo adalah Proyek Ideal:Robot sumo kecil, murah, dan menantang. Ia adalah proyek ideal untuk memahami robotika secara holistik.',
                        'card:ESP32 adalah Otak:ESP32 adalah mikrokontroler dengan WiFi dan Bluetooth terintegrasi. Ia adalah otak di balik RoboLab.',
                        '---',
                        '### Target Kompetensi Pertemuan 1',
                        'skill:100%:Memahami kontrak kuliah dan RPS 16 pertemuan:Wajib',
                        'skill:95%:Menjelaskan definisi dan ruang lingkup robotika:Wajib',
                        'skill:90%:Menyiapkan alat kerja robotika:Wajib',
                        'skill:75%:Mengidentifikasi aplikasi robotika di industri:Pengayaan',
                        '---',
                        '### Ringkasan Aktivitas',
                        'table:[{"Aktivitas": "Pembukaan dan kontrak kuliah", "Deskripsi": "Menyepakati aturan, bobot penilaian, dan ekspektasi", "Durasi": "20 menit"}, {"Aktivitas": "Ceramah pengantar robotika dan RoboLab", "Deskripsi": "Menelusuri peta materi dan arsitektur proyek payung", "Durasi": "40 menit"}, {"Aktivitas": "Demo ESP32 dan WiFi", "Deskripsi": "Menyalakan LED melalui web browser via WiFi ESP32", "Durasi": "30 menit"}, {"Aktivitas": "Setup alat dan repo", "Deskripsi": "Membuat repo tim, menyiapkan ESP32 dan komponen, memverifikasi lingkungan", "Durasi": "10 menit"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul02',
                    title: 'Pertemuan 2: Definisi, Sejarah, dan Jenis Robot',
                    lines: [
                        '**Pertemuan 2: Definisi, Sejarah, dan Jenis Robot**',
                        '*Dari mainan otomatis Yunani kuno hingga robot humanoid modern — perjalanan robotika adalah cermin perjalanan peradaban manusia.*',
                        '---',
                        'Pertemuan ini memperkenalkan definisi robot, sejarah perkembangannya, jenis dan fungsi robot, serta interaksi manusia dengan robot. Anda akan memahami konteks historis dan konseptual dari robotika.',
                        'Materi ini adalah inti CPL-2 dan menjadi fondasi untuk memahami perancangan robot di pertemuan berikutnya.',
                        '---',
                        '### Mengapa Memahami Definisi dan Sejarah Robot Penting?',
                        'card:Definisi Menentukan Batas:Ada banyak definisi robot, dari yang sederhana hingga yang kompleks. Memahami definisi membantu Anda menentukan apa yang termasuk robot dan apa yang tidak.',
                        'card:Sejarah Memberi Konteks:Memahami sejarah robotika membantu Anda memahami mengapa teknologi saat ini berkembang seperti sekarang, dan ke mana arahnya.',
                        'card:Jenis Menentukan Pendekatan:Robot industri, mobile robot, dan humanoid memiliki karakteristik berbeda. Memahami jenis membantu Anda memilih pendekatan yang tepat.',
                        '---',
                        '### Definisi dan Sejarah Robot',
                        'Kata "robot" berasal dari bahasa Ceko "robota" yang berarti pekerja paksa. Sejak Karel Čapek memperkenalkannya pada 1920, makna robot telah berkembang pesat.',
                        '```javascript',
                        '// Linimasa sejarah robotika\nconst LINIMASA_ROBOT = [\n    { tahun: 1920, peristiwa: \'Karel Čapek memperkenalkan istilah "robot" dalam drama R.U.R.\' },\n    { tahun: 1954, peristiwa: \'George Devol mempatenkan robot industri pertama, Unimate\' },\n    { tahun: 1961, peristiwa: \'Unimate mulai bekerja di pabrik General Motors\' },\n    { tahun: 1997, peristiwa: \'Sojourner menjelajahi Mars\' },\n    { tahun: 2000, peristiwa: \'ASIMO humanoid diperkenalkan Honda\' },\n    { tahun: 2012, peristiwa: \'Curiosity mendarat di Mars\' },\n    { tahun: 2020, peristiwa: \'Robot layanan dan drone menjadi umum\' }\n];\n\nLINIMASA_ROBOT.forEach(item => {\n    console.log(`${item.tahun} — ${item.peristiwa}`);\n});',
                        '```',
                        '---',
                        '### Jenis dan Fungsi Robot',
                        'Robot dapat diklasifikasikan berdasarkan lingkungan kerja, fungsi, dan tingkat otonomi. Berikut klasifikasi yang paling umum dipakai di industri.',
                        '```javascript',
                        '// Klasifikasi robot\nconst JENIS_ROBOT = {\n    industri: {\n        contoh: [\'Robot las\', \'Robot perakitan\', \'Robot pengecatan\'],\n        ciri: \'Tetap di tempat, presisi tinggi, tugas berulang\'\n    },\n    mobile: {\n        contoh: [\'AGV\', \'Robot vacuum\', \'Drone\'],\n        ciri: \'Bergerak, navigasi, sensor beragam\'\n    },\n    humanoid: {\n        contoh: [\'ASIMO\', \'Atlas\', \'Pepper\'],\n        ciri: \'Menyerupai manusia, interaksi sosial\'\n    },\n    medis: {\n        contoh: [\'Da Vinci Surgical\', \'Robot rehabilitasi\'],\n        ciri: \'Presisi tinggi, keamanan kritis\'\n    }\n};\n\nfor (const [kategori, info] of Object.entries(JENIS_ROBOT)) {\n    console.log(kategori.toUpperCase(), \'→\', info.ciri);\n}',
                        '```',
                        '---',
                        '### Interaksi Manusia dan Robot',
                        'Interaksi manusia-robot (HRI) adalah bidang yang mempelajari bagaimana manusia dan robot berkomunikasi dan bekerja sama. Ini penting untuk robot layanan dan kolaboratif.',
                        'table:[{"Aspek": "Antarmuka", "Contoh": "Layar sentuh, suara, gesture", "Tantangan": "Intuitif dan aman"}, {"Aspek": "Keamanan", "Contoh": "Sensor tabrakan, batas kecepatan", "Tantangan": "Mencegah cedera"}, {"Aspek": "Kepercayaan", "Contoh": "Transparansi keputusan robot", "Tantangan": "Membangun kepercayaan pengguna"}, {"Aspek": "Etika", "Contoh": "Privasi, otonomi, akuntabilitas", "Tantangan": "Regulasi dan norma sosial"}]',
                        '---',
                        '### 3 Konsep Inti Definisi dan Jenis Robot',
                        'card:Definisi Robot Beragam:Tidak ada satu definisi tunggal untuk robot. Setiap definisi menekankan aspek berbeda: otonomi, sensor, aktuator, atau kecerdasan.',
                        'card:Sejarah Memberi Konteks:Robotika berkembang dari otomasi industri hingga robot cerdas. Memahami sejarah membantu memahami arah perkembangan.',
                        'card:Jenis Menentukan Pendekatan:Setiap jenis robot memerlukan pendekatan berbeda dalam desain, kontrol, dan interaksi.',
                        '---',
                        '### Target Kompetensi Pertemuan 2',
                        'skill:100%:Menjelaskan definisi dan sejarah robot:Wajib',
                        'skill:95%:Mengklasifikasikan jenis dan fungsi robot:Wajib',
                        'skill:90%:Menjelaskan interaksi manusia-robot:Wajib',
                        'skill:80%:Menganalisis aplikasi robot di industri:Pengayaan',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Linimasa robotika", "Deskripsi": "Buat linimasa visual sejarah robotika, tandai tonggak penting"}, {"Aktivitas": "Klasifikasi robot", "Deskripsi": "Pilih 5 robot nyata, klasifikasikan berdasarkan jenis dan fungsi"}, {"Aktivitas": "Analisis HRI", "Deskripsi": "Pilih satu robot layanan, analisis aspek interaksi manusia-robotnya"}, {"Aktivitas": "Dokumentasi", "Deskripsi": "Tulis ringkasan definisi dan jenis robot di README repo robo-lab"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul03',
                    title: 'Pertemuan 3: Teknik Perancangan dan Sistem Kontroler',
                    lines: [
                        '**Pertemuan 3: Teknik Perancangan dan Sistem Kontroler**',
                        '*Robot yang baik bukan yang paling canggih, melainkan yang paling tepat menjawab kebutuhan.*',
                        '---',
                        'Pertemuan ini membahas teknik perancangan robot dan sistem kontroler. Anda akan mempelajari pendekatan sistematis dalam merancang robot, dari spesifikasi kebutuhan hingga arsitektur kontrol.',
                        'Materi ini adalah inti CPL-3 dan menjadi fondasi untuk perancangan mekanik dan sistem kendali di pertemuan berikutnya.',
                        '---',
                        '### Mengapa Teknik Perancangan dan Kontroler Penting?',
                        'card:Perancangan Menentukan Keberhasilan:Robot yang dirancang dengan baik akan mudah dirakit, diprogram, dan dipelihara. Perancangan yang buruk menghasilkan robot yang rapuh dan sulit dikendalikan.',
                        'card:Kontroler adalah Otak: Sistem kontroler menentukan bagaimana robot merespons sensor dan mengendalikan aktuator. Ia adalah otak di balik perilaku robot.',
                        'card:Spesifikasi adalah Kompas:Spesifikasi kebutuhan adalah kompas perancangan. Tanpa spesifikasi yang jelas, perancangan akan melenceng dari tujuan.',
                        '---',
                        '### Tahapan Perancangan Robot',
                        'Perancangan robot mengikuti siklus yang sistematis: dari spesifikasi kebutuhan hingga pengujian. Setiap tahap memiliki keluaran yang jelas.',
                        '```javascript',
                        '// Tahapan perancangan robot\nconst TAHAPAN_PERANCANGAN = [\n    \'1. Spesifikasi kebutuhan (apa yang harus dilakukan robot?)\',\n    \'2. Perancangan konseptual (arsitektur umum)\',\n    \'3. Perancangan mekanik (rangka, roda, aktuator)\',\n    \'4. Perancangan elektronik (sensor, kontroler, daya)\',\n    \'5. Perancangan perangkat lunak (firmware, kontrol)\',\n    \'6. Integrasi dan pengujian\',\n    \'7. Iterasi dan penyempurnaan\'\n];\n\nTAHAPAN_PERANCANGAN.forEach(t => console.log(t));',
                        '```',
                        '---',
                        '### Sistem Kontroler',
                        'Sistem kontroler robot terdiri dari tiga komponen utama: sensor (input), kontroler (proses), dan aktuator (output). Loop kontrol menghubungkan ketiganya.',
                        '```javascript',
                        '// Loop kontrol dasar\nclass KontrolerRobot {\n    constructor(setpoint) {\n        this.setpoint = setpoint;\n        this.error = 0;\n        this.output = 0;\n    }\n\n    bacaSensor(nilaiAktual) {\n        this.error = this.setpoint - nilaiAktual;\n        return this.error;\n    }\n\n    hitungKontrol() {\n        // Kontrol proporsional sederhana\n        const Kp = 1.5;\n        this.output = Kp * this.error;\n        return this.output;\n    }\n\n    kirimKeAktuator() {\n        console.log(\'Output kontrol:\', this.output.toFixed(2));\n        return this.output;\n    }\n}\n\nconst kontroler = new KontrolerRobot(100);\nkontroler.bacaSensor(80);\nkontroler.hitungKontrol();\nkontroler.kirimKeAktuator();',
                        '```',
                        '---',
                        '### Arsitektur Kontrol',
                        'Ada beberapa arsitektur kontrol yang umum dipakai: reaktif, deliberatif, dan hybrid. Masing-masing memiliki kelebihan dan keterbatasan.',
                        'table:[{"Arsitektur": "Reaktif", "Karakteristik": "Respons langsung ke sensor", "Cocok Untuk": "Tugas sederhana, real-time"}, {"Arsitektur": "Deliberatif", "Karakteristik": "Perencanaan sebelum bertindak", "Cocok Untuk": "Tugas kompleks, navigasi"}, {"Arsitektur": "Hybrid", "Karakteristik": "Kombinasi reaktif dan deliberatif", "Cocok Untuk": "Robot otonom modern"}, {"Arsitektur": "Behavior-based", "Karakteristik": "Kumpulan perilaku sederhana", "Cocok Untuk": "Robot sumo, robot sosial"}]',
                        '---',
                        '### 3 Konsep Inti Perancangan dan Kontroler',
                        'card:Spesifikasi adalah Fondasi:Tanpa spesifikasi yang jelas, perancangan tidak punya arah. Luangkan waktu untuk mendefinisikan kebutuhan dengan tepat.',
                        'card:Kontroler adalah Otak:Kontroler mengubah input sensor menjadi output aktuator. Ia adalah inti dari perilaku robot.',
                        'card:Iterasi adalah Normal:Perancangan robot adalah proses iteratif. Rancangan pertama hampir selalu perlu perbaikan.',
                        '---',
                        '### Target Kompetensi Pertemuan 3',
                        'skill:100%:Menjelaskan tahapan perancangan robot:Wajib',
                        'skill:95%:Merancang sistem kontroler dasar:Wajib',
                        'skill:90%:Memilih arsitektur kontrol yang tepat:Wajib',
                        'skill:80%:Menyusun spesifikasi kebutuhan robot:Pengayaan',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Spesifikasi robot sumo", "Deskripsi": "Susun spesifikasi kebutuhan untuk robot sumo RoboLab"}, {"Aktivitas": "Diagram arsitektur", "Deskripsi": "Buat diagram arsitektur kontrol robot sumo (sensor, kontroler, aktuator)"}, {"Aktivitas": "Loop kontrol", "Deskripsi": "Implementasikan loop kontrol proporsional sederhana di JavaScript"}, {"Aktivitas": "Dokumentasi", "Deskripsi": "Dokumentasikan spesifikasi dan arsitektur di README repo robo-lab"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul04',
                    title: 'Pertemuan 4: Mekanik Robot',
                    lines: [
                        '**Pertemuan 4: Mekanik Robot**',
                        '*Mekanik adalah tubuh robot. Tanpa mekanik yang baik, kecerdasan tidak berarti apa-apa.*',
                        '---',
                        'Pertemuan ini membahas mekanik robot: rangka, roda, aktuator, transmisi, dan derajat kebebasan. Anda akan mempelajari bagaimana merancang mekanik robot yang kokoh, efisien, dan sesuai kebutuhan.',
                        'Materi ini adalah inti CPL-4 dan menjadi fondasi untuk perancangan robot sumo RoboLab.',
                        '---',
                        '### Mengapa Mekanik Robot Penting?',
                        'card:Mekanik Menentukan Kemampuan:Roda, motor, dan rangka menentukan kecepatan, torsi, dan kemampuan manuver robot. Mekanik yang buruk membatasi kemampuan robot.',
                        'card:Derajat Kebebasan Menentukan Fleksibilitas:Jumlah derajat kebebasan (DOF) menentukan seberapa fleksibel robot bergerak. Robot sumo biasanya 2 DOF (diferensial).',
                        'card:Transmisi Menentukan Efisiensi:Transmisi yang tepat menyalurkan tenaga motor ke roda secara efisien. Transmisi yang buruk membuang energi.',
                        '---',
                        '### Komponen Mekanik Robot',
                        'Robot sumo memiliki komponen mekanik yang sederhana namun kritis: rangka, motor, roda, dan sirip (blade) untuk mendorong lawan.',
                        '```javascript',
                        '// Komponen mekanik robot sumo\nconst MEKANIK_ROBOT_SUMO = {\n    rangka: {\n        material: \'Akrilik atau aluminium\',\n        fungsi: \'Menopang semua komponen\',\n        catatan: \'Ringan namun kokoh\'\n    },\n    motor: {\n        tipe: \'DC gearbox\',\n        tegangan: \'6-12V\',\n        fungsi: \'Menggerakkan roda\',\n        catatan: \'Pilih torsi tinggi untuk mendorong\'\n    },\n    roda: {\n        tipe: \'Roda karet\',\n        diameter: \'65mm\',\n        fungsi: \'Kontak dengan arena\',\n        catatan: \'Grip tinggi untuk traksi\'\n    },\n    blade: {\n        material: \'Aluminium atau besi\',\n        fungsi: \'Mendorong lawan keluar arena\',\n        catatan: \'Sudut dan tinggi menentukan efektivitas\'\n    }\n};\n\nconsole.log(\'Komponen mekanik:\', Object.keys(MEKANIK_ROBOT_SUMO));',
                        '```',
                        '---',
                        '### Derajat Kebebasan (DOF)',
                        'Derajat kebebasan adalah jumlah parameter independen yang menentukan konfigurasi robot. Robot sumo diferensial memiliki 2 DOF: maju/mundur dan rotasi.',
                        '```javascript',
                        '// Kinematika roda diferensial\n// Robot sumo dengan 2 roda: kiri dan kanan\nclass RobotDiferensial {\n    constructor(jarakRoda) {\n        this.jarakRoda = jarakRoda; // meter\n    }\n\n    // Kecepatan linear dan angular dari kecepatan roda\n    hitungGerak(vKiri, vKanan) {\n        const v = (vKiri + vKanan) / 2;\n        const omega = (vKanan - vKiri) / this.jarakRoda;\n        return { linear: v, angular: omega };\n    }\n\n    // Kecepatan roda dari kecepatan linear dan angular\n    hitungRoda(v, omega) {\n        const vKiri = v - (omega * this.jarakRoda) / 2;\n        const vKanan = v + (omega * this.jarakRoda) / 2;\n        return { kiri: vKiri, kanan: vKanan };\n    }\n}\n\nconst robot = new RobotDiferensial(0.15);\nconsole.log(\'Gerak:\', robot.hitungGerak(0.5, 0.7));\nconsole.log(\'Roda:\', robot.hitungRoda(0.5, 1.0));',
                        '```',
                        '---',
                        '### Transmisi dan Torsi',
                        'Transmisi menyalurkan tenaga dari motor ke roda. Gearbox mengurangi kecepatan tetapi menambah torsi — penting untuk robot sumo yang perlu mendorong lawan.',
                        'table:[{"Komponen": "Motor DC", "Fungsi": "Sumber tenaga", "Spesifikasi": "Tegangan, arus, RPM"}, {"Komponen": "Gearbox", "Fungsi": "Mengubah kecepatan dan torsi", "Spesifikasi": "Rasio gear"}, {"Komponen": "Roda", "Fungsi": "Kontak dengan permukaan", "Spesifikasi": "Diameter, material, grip"}, {"Komponen": "Bearing", "Fungsi": "Mengurangi gesekan", "Spesifikasi": "Ukuran, tipe"}]',
                        '---',
                        '### 3 Konsep Inti Mekanik Robot',
                        'card:Mekanik adalah Tubuh:Mekanik menentukan kemampuan fisik robot. Tanpa mekanik yang baik, kecerdasan tidak berarti.',
                        'card:DOF Menentukan Fleksibilitas:Jumlah derajat kebebasan menentukan seberapa fleksibel robot bergerak. Robot sumo diferensial memiliki 2 DOF.',
                        'card:Transmisi Menentukan Efisiensi:Transmisi yang tepat menyalurkan tenaga motor ke roda secara efisien. Gearbox mengurangi kecepatan tetapi menambah torsi.',
                        '---',
                        '### Target Kompetensi Pertemuan 4',
                        'skill:100%:Menjelaskan komponen mekanik robot:Wajib',
                        'skill:95%:Menerapkan kinematika roda diferensial:Wajib',
                        'skill:90%:Memilih motor dan roda yang tepat:Wajib',
                        'skill:80%:Merancang mekanik robot sumo:Pengayaan',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Analisis kinematika", "Deskripsi": "Hitung kecepatan linear dan angular robot dari kecepatan roda"}, {"Aktivitas": "Pemilihan motor", "Deskripsi": "Bandingkan 3 motor DC, pilih yang paling sesuai untuk robot sumo"}, {"Aktivitas": "Desain rangka", "Deskripsi": "Rancang rangka robot sumo di kertas atau software CAD sederhana"}, {"Aktivitas": "Dokumentasi mekanik", "Deskripsi": "Dokumentasikan komponen mekanik dan alasan pemilihannya di README repo robo-lab"}]',
                        '---',
                    ],
                },
            ],
        },

                {
            name: 'Bagian 2: Sensor, Aktuator, dan UTS',
            items: [
                {
                    id: 'modul05',
                    title: 'Pertemuan 5: Sistem Sensor dan Aktuator',
                    lines: [
                        '**Pertemuan 5: Sistem Sensor dan Aktuator**',
                        '*Sensor adalah indra robot. Aktuator adalah ototnya. Tanpa keduanya, robot hanyalah rangka mati.*',
                        '---',
                        'Pertemuan ini membahas sistem sensor dan aktuator pada robot. Anda akan mempelajari berbagai jenis sensor, karakteristiknya, serta aktuator yang menggerakkan robot — semuanya dalam konteks robot sumo RoboLab.',
                        'Materi ini adalah inti CPL-5 dan menjadi fondasi untuk sistem kendali di pertemuan berikutnya.',
                        '---',
                        '### Mengapa Sensor dan Aktuator Penting?',
                        'card:Sensor adalah Indra:Robot tanpa sensor tidak bisa merasakan lingkungannya. Sensor ultrasonik, inframerah, dan IMU adalah indra utama robot sumo.',
                        'card:Aktuator adalah Otot:Motor DC, servo, dan stepper adalah aktuator yang menggerakkan robot. Pemilihan aktuator menentukan kecepatan dan torsi robot.',
                        'card:Kalibrasi Menentukan Akurasi:Sensor perlu dikalibrasi agar akurat. Kalibrasi yang buruk menghasilkan keputusan yang salah.',
                        '---',
                        '### Jenis Sensor pada Robot Sumo',
                        'Robot sumo RoboLab menggunakan tiga jenis sensor utama: ultrasonik untuk mendeteksi lawan, inframerah untuk mendeteksi garis arena, dan IMU untuk orientasi.',
                        '```javascript',
                        '// Jenis sensor pada robot sumo\nclass SensorUltrasonik {\n    constructor(triggerPin, echoPin) {\n        this.triggerPin = triggerPin;\n        this.echoPin = echoPin;\n    }\n\n    // Simulasi pembacaan jarak (cm)\n    bacaJarak() {\n        return 50 + Math.random() * 100;\n    }\n\n    deteksiLawan(ambang = 100) {\n        return this.bacaJarak() < ambang;\n    }\n}\n\nclass SensorInframerah {\n    constructor(pin) {\n        this.pin = pin;\n    }\n\n    // Simulasi deteksi garis (true = garis terdeteksi)\n    deteksiGaris() {\n        return Math.random() > 0.5;\n    }\n}\n\nclass IMU {\n    constructor() {\n        this.orientasi = 0;\n    }\n\n    bacaOrientasi() {\n        this.orientasi += (Math.random() - 0.5) * 5;\n        return this.orientasi;\n    }\n}\n\nconst ultra = new SensorUltrasonik(5, 18);\nconsole.log(\'Jarak:\', ultra.bacaJarak().toFixed(1), \'cm\');\nconsole.log(\'Lawan terdeteksi:\', ultra.deteksiLawan());',
                        '```',
                        '---',
                        '### Aktuator: Motor DC dan Driver',
                        'Motor DC adalah aktuator utama robot sumo. Ia dikendalikan melalui motor driver seperti L298N yang memungkinkan pengaturan arah dan kecepatan.',
                        '```javascript',
                        '// Kontrol motor DC melalui driver L298N\nclass MotorDC {\n    constructor(pinA, pinB, pinPWM) {\n        this.pinA = pinA;\n        this.pinB = pinB;\n        this.pinPWM = pinPWM;\n        this.kecepatan = 0;\n        this.arah = \'berhenti\';\n    }\n\n    maju(kecepatan) {\n        this.arah = \'maju\';\n        this.kecepatan = Math.min(255, Math.max(0, kecepatan));\n        console.log(`Motor ${this.pinA} maju dengan PWM ${this.kecepatan}`);\n    }\n\n    mundur(kecepatan) {\n        this.arah = \'mundur\';\n        this.kecepatan = Math.min(255, Math.max(0, kecepatan));\n        console.log(`Motor ${this.pinA} mundur dengan PWM ${this.kecepatan}`);\n    }\n\n    berhenti() {\n        this.arah = \'berhenti\';\n        this.kecepatan = 0;\n        console.log(`Motor ${this.pinA} berhenti`);\n    }\n}\n\nconst motorKiri = new MotorDC(12, 13, 14);\nconst motorKanan = new MotorDC(25, 26, 27);\n\nmotorKiri.maju(200);\nmotorKanan.maju(200);\nconsole.log(\'Robot bergerak maju\');',
                        '```',
                        '---',
                        '### Karakteristik Sensor',
                        'Setiap sensor memiliki karakteristik yang memengaruhi pemilihan dan penggunaannya. Memahami karakteristik ini adalah kunci desain sistem yang baik.',
                        'table:[{"Sensor": "Ultrasonik", "Rentang": "2-400 cm", "Kegunaan": "Deteksi lawan", "Keterbatasan": "Terpengaruh sudut dan permukaan"}, {"Sensor": "Inframerah", "Rentang": "0.5-30 cm", "Kegunaan": "Deteksi garis", "Keterbatasan": "Terpengaruh warna dan cahaya"}, {"Sensor": "IMU", "Rentang": "Orientasi", "Kegunaan": "Stabilisasi arah", "Keterbatasan": "Drift seiring waktu"}, {"Sensor": "Encoder", "Rentang": "Rotasi", "Kegunaan": "Odometri", "Keterbatasan": "Perlu kalibrasi"}]',
                        '---',
                        '### 3 Konsep Inti Sensor dan Aktuator',
                        'card:Sensor adalah Indra:Robot tanpa sensor tidak bisa merasakan lingkungannya. Sensor ultrasonik, inframerah, dan IMU adalah indra utama robot sumo.',
                        'card:Aktuator adalah Otot:Motor DC adalah aktuator utama robot sumo. Driver mengatur arah dan kecepatan motor.',
                        'card:Kalibrasi Menentukan Akurasi:Sensor perlu dikalibrasi agar akurat. Kalibrasi yang buruk menghasilkan keputusan yang salah.',
                        '---',
                        '### Target Kompetensi Pertemuan 5',
                        'skill:100%:Menjelaskan jenis dan karakteristik sensor:Wajib',
                        'skill:95%:Mengendalikan motor DC melalui driver:Wajib',
                        'skill:90%:Mengimplementasikan deteksi lawan dan garis:Wajib',
                        'skill:85%:Mengkalibrasi sensor untuk akurasi:Pengayaan',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Baca sensor ultrasonik", "Deskripsi": "Baca jarak dengan HC-SR04, uji pada berbagai kondisi"}, {"Aktivitas": "Kontrol motor DC", "Deskripsi": "Kendalikan dua motor DC melalui L298N, uji maju, mundur, berhenti"}, {"Aktivitas": "Deteksi garis", "Deskripsi": "Baca sensor inframerah, uji deteksi garis hitam di arena putih"}, {"Aktivitas": "Firmware dasar", "Deskripsi": "Upload firmware dasar ke ESP32 yang menggabungkan sensor dan aktuator"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul06',
                    title: 'Pertemuan 6: Sistem Kendali pada Robot',
                    lines: [
                        '**Pertemuan 6: Sistem Kendali pada Robot**',
                        '*Robot yang baik bukan yang paling cepat, melainkan yang paling tepat mengambil keputusan pada waktu yang tepat.*',
                        '---',
                        'Pertemuan ini membahas sistem kendali pada robot: kendali kecepatan dan posisi, PID, umpan balik, dan kalibrasi. Anda akan mempelajari bagaimana robot mengambil keputusan berdasarkan input sensor dan mengendalikan aktuator.',
                        'Materi ini adalah inti CPL-6 dan menjadi fondasi untuk kendali otonom robot sumo.',
                        '---',
                        '### Mengapa Sistem Kendali Penting?',
                        'card:Kendali Menentukan Perilaku:Sistem kendali menentukan bagaimana robot merespons sensor dan mengendalikan aktuator. Ia adalah otak di balik perilaku robot.',
                        'card:PID adalah Standar:PID (Proportional-Integral-Derivative) adalah algoritma kendali paling umum di industri. Memahaminya membuka banyak aplikasi.',
                        'card:Umpan Balik Menentukan Akurasi:Umpan balik memungkinkan robot mengoreksi kesalahan secara real-time. Tanpa umpan balik, robot tidak bisa beradaptasi.',
                        '---',
                        '### Kendali Kecepatan dan Posisi',
                        'Kendali kecepatan mengatur seberapa cepat motor berputar. Kendali posisi mengatur di mana motor berhenti. Keduanya bekerja dengan prinsip umpan balik.',
                        '```javascript',
                        '// Kendali kecepatan motor dengan umpan balik\nclass KendaliKecepatan {\n    constructor(setpoint, Kp = 1.5) {\n        this.setpoint = setpoint;\n        this.Kp = Kp;\n        this.error = 0;\n    }\n\n    hitung(kecepatanAktual) {\n        this.error = this.setpoint - kecepatanAktual;\n        const output = this.Kp * this.error;\n        return Math.min(255, Math.max(-255, output));\n    }\n}\n\nconst kendali = new KendaliKecepatan(200);\nconsole.log(\'Output kontrol:\', kendali.hitung(150));\nconsole.log(\'Output kontrol:\', kendali.hitung(180));\nconsole.log(\'Output kontrol:\', kendali.hitung(210));',
                        '```',
                        '---',
                        '### PID Controller',
                        'PID menggabungkan tiga komponen: Proporsional (P), Integral (I), dan Derivatif (D). Masing-masing menangani aspek berbeda dari error.',
                        '```javascript',
                        '// PID Controller\nclass PID {\n    constructor(Kp, Ki, Kd) {\n        this.Kp = Kp;\n        this.Ki = Ki;\n        this.Kd = Kd;\n        this.errorSebelumnya = 0;\n        this.integral = 0;\n    }\n\n    hitung(setpoint, aktual, dt = 0.1) {\n        const error = setpoint - aktual;\n        this.integral += error * dt;\n        const derivatif = (error - this.errorSebelumnya) / dt;\n        const output = this.Kp * error + this.Ki * this.integral + this.Kd * derivatif;\n        this.errorSebelumnya = error;\n        return output;\n    }\n}\n\nconst pid = new PID(1.5, 0.1, 0.05);\nconsole.log(\'PID output:\', pid.hitung(100, 80).toFixed(2));\nconsole.log(\'PID output:\', pid.hitung(100, 90).toFixed(2));\nconsole.log(\'PID output:\', pid.hitung(100, 95).toFixed(2));',
                        '```',
                        '---',
                        '### Strategi Kendali Robot Sumo',
                        'Robot sumo memerlukan strategi kendali yang menggabungkan pencarian lawan, penyerangan, dan pertahanan. Strategi ini diimplementasikan sebagai mesin state.',
                        'table:[{"State": "Mencari", "Aksi": "Berputar mencari lawan", "Transisi": "Lawan terdeteksi"}, {"State": "Menyerang", "Aksi": "Maju cepat ke arah lawan", "Transisi": "Lawan hilang atau garis terdeteksi"}, {"State": "Menghindari Garis", "Aksi": "Mundur dan berputar", "Transisi": "Aman dari garis"}, {"State": "Bertahan", "Aksi": "Berputar cepat di tempat", "Transisi": "Lawan terdeteksi"}]',
                        '---',
                        '### 3 Konsep Inti Sistem Kendali',
                        'card:Kendali adalah Keputusan:Sistem kendali mengubah input sensor menjadi keputusan aktuator. Ia adalah inti perilaku robot.',
                        'card:PID adalah Standar:PID menggabungkan proporsional, integral, dan derivatif. Ia adalah algoritma kendali paling umum di industri.',
                        'card:Umpan Balik Menentukan Adaptasi:Umpan balik memungkinkan robot mengoreksi kesalahan secara real-time. Tanpa umpan balik, robot tidak bisa beradaptasi.',
                        '---',
                        '### Target Kompetensi Pertemuan 6',
                        'skill:100%:Menjelaskan kendali kecepatan dan posisi:Wajib',
                        'skill:95%:Mengimplementasikan PID controller:Wajib',
                        'skill:90%:Merancang strategi kendali robot sumo:Wajib',
                        'skill:85%:Mengkalibrasi parameter PID:Pengayaan',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Kendali kecepatan", "Deskripsi": "Implementasikan kendali kecepatan motor dengan umpan balik encoder"}, {"Aktivitas": "PID tuning", "Deskripsi": "Tuning parameter PID untuk kendali posisi robot, catat responsnya"}, {"Aktivitas": "Mesin state", "Deskripsi": "Implementasikan mesin state untuk strategi robot sumo (mencari, menyerang, menghindar)"}, {"Aktivitas": "Uji di arena", "Deskripsi": "Uji strategi kendali di arena mini, catat keberhasilan dan perbaiki"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul07',
                    title: 'Pertemuan 7: Review dan Integrasi P2–P6',
                    lines: [
                        '**Pertemuan 7: Review dan Integrasi P2–P6**',
                        '*Ujian bukan tentang menghafal, tetapi tentang menghubungkan titik-titik yang sudah Anda pelajari.*',
                        '---',
                        'Pertemuan ini adalah jembatan menuju UTS. Kita akan mengulang materi P2–P6 secara terstruktur, mengintegrasikan konsep dari definisi robot hingga sistem kendali, serta berlatih soal-soal yang menuntut pemahaman.',
                        'Manfaatkan pertemuan ini untuk mengidentifikasi celah pemahaman Anda sebelum UTS.',
                        '---',
                        '### Yang Sudah Harus Anda Bisa',
                        'card:Menjelaskan Jenis dan Sejarah Robot:Anda harus bisa menjelaskan definisi, sejarah, jenis, dan fungsi robot, serta interaksi manusia-robot.',
                        'card:Merancang Robot Sederhana:Anda harus bisa menyusun spesifikasi kebutuhan, merancang mekanik dasar, dan memilih sensor serta aktuator yang tepat.',
                        'card:Menerapkan Kendali Dasar:Anda harus bisa mengimplementasikan loop kontrol sederhana dan menjelaskan peran umpan balik dalam sistem kendali.',
                        '---',
                        '### Checklist Persiapan UTS',
                        '```javascript',
                        '// Checklist mandiri sebelum UTS\nconst CHECKLIST_UTS = [\n    \'✅ Bisa menjelaskan definisi dan sejarah robot\',\n    \'✅ Bisa mengklasifikasikan jenis dan fungsi robot\',\n    \'✅ Bisa menjelaskan interaksi manusia-robot\',\n    \'✅ Bisa menyusun spesifikasi kebutuhan robot\',\n    \'✅ Bisa menjelaskan tahapan perancangan robot\',\n    \'✅ Bisa menerapkan kinematika roda diferensial\',\n    \'✅ Bisa menjelaskan jenis dan karakteristik sensor\',\n    \'✅ Bisa mengendalikan motor DC melalui driver\',\n    \'✅ Bisa mengimplementasikan kendali kecepatan\',\n    \'✅ Bisa menjelaskan PID controller\'\n];\n\nCHECKLIST_UTS.forEach(item => console.log(item));',
                        '```',
                        '---',
                        '### Integration Lab',
                        'Latihan integrasi berikut menggabungkan konsep dari beberapa pertemuan sekaligus. Kerjakan minimal dua di antaranya sebelum UTS.',
                        'table:[{"Skenario": "Sensor + aktuator", "Menggabungkan": "P4, P5", "Output": "Robot yang bergerak berdasarkan sensor"}, {"Skenario": "Kendali + sensor", "Menggabungkan": "P5, P6", "Output": "Kendali kecepatan dengan umpan balik sensor"}, {"Skenario": "Perancangan + mekanik", "Menggabungkan": "P3, P4", "Output": "Spesifikasi dan rancangan mekanik robot sumo"}, {"Skenario": "Integrasi penuh", "Menggabungkan": "P2–P6", "Output": "Prototipe robot sumo sederhana"}]',
                        '---',
                        '### 3 Konsep Inti Review',
                        'card:Integrasi adalah Tujuan:Materi P2–P6 bukan potongan terpisah. UTS menguji kemampuan Anda merangkainya menjadi sistem robot yang koheren.',
                        'card:Desain adalah Kunci:UTS akan menguji kemampuan Anda merancang robot dan sistem kendalinya, bukan hanya menghafal istilah.',
                        'card:Praktik adalah Bukti:Bagian praktik UTS menguji apakah Anda benar-benar bisa membangun dan mengendalikan robot sederhana.',
                        '---',
                        '### Target Kompetensi Pertemuan 7',
                        'skill:100%:Menguasai definisi, jenis, dan perancangan robot:Wajib',
                        'skill:95%:Menerapkan kinematika dan mekanik robot:Wajib',
                        'skill:90%:Mengimplementasikan sensor dan aktuator:Wajib',
                        'skill:85%:Merancang sistem kendali dasar:Kesiapan UTS',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Latihan soal terstruktur", "Deskripsi": "Kerjakan 10 soal analisis tentang robotika dan sistem kendali"}, {"Aktivitas": "Integration lab", "Deskripsi": "Pilih dua skenario integrasi, kerjakan, presentasikan hasilnya"}, {"Aktivitas": "Peer review", "Deskripsi": "Review rancangan robot kelompok lain, beri masukan konstruktif"}, {"Aktivitas": "Konsolidasi catatan", "Deskripsi": "Susun catatan ringkas satu halaman per pertemuan P2–P6 sebagai bekal UTS"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul08',
                    title: 'Pertemuan 8: UTS — Evaluasi Tengah Semester',
                    lines: [
                        '**Pertemuan 8: UTS — Evaluasi Tengah Semester**',
                        '*Ujian adalah cermin. Ia menunjukkan bukan hanya apa yang Anda tahu, tetapi bagaimana Anda berpikir.*',
                        '---',
                        'UTS mengevaluasi pemahaman Anda atas materi P2–P6: definisi dan jenis robot, teknik perancangan, mekanik robot, sensor dan aktuator, serta sistem kendali. Ujian terdiri dari bagian tertulis dan bagian desain.',
                        'Siapkan diri Anda dengan memahami konsep, bukan menghafal sintaksis. Sintaksis bisa dicari, pemahaman tidak.',
                        '---',
                        '### Strategi Sukses UTS',
                        'card:Kuasai Konsep Dasar:UTS sering meminta Anda menjelaskan definisi, jenis, dan perancangan robot. Pahami, jangan hafal.',
                        'card:Latih Desain Robot:Soal desain menuntut Anda merancang robot sumo sederhana dengan sensor, aktuator, dan strategi kendali yang tepat.',
                        'card:Jelaskan Trade-off:Soal analisis menuntut Anda membandingkan pilihan desain. Siapkan argumen mengapa memilih motor A daripada motor B, atau PID daripada kendali proporsional.',
                        '---',
                        '### Rubrik Penilaian UTS',
                        'table:[{"Kriteria": "Konsep dasar robotika", "Bobot": "20%", "Indikator": "Menjelaskan definisi, sejarah, jenis, dan fungsi robot"}, {"Kriteria": "Perancangan dan mekanik", "Bobot": "25%", "Indikator": "Merancang robot sumo dengan spesifikasi dan mekanik yang tepat"}, {"Kriteria": "Sensor dan aktuator", "Bobot": "30%", "Indikator": "Memilih sensor dan aktuator, menjelaskan karakteristiknya"}, {"Kriteria": "Sistem kendali", "Bobot": "25%", "Indikator": "Merancang loop kendali dan menjelaskan peran umpan balik"}]',
                        '---',
                        '### Kerangka Jawaban yang Boleh Dihafal',
                        '```javascript',
                        '// Kerangka jawaban soal desain robot\n// 1. Spesifikasi kebutuhan\n//    - apa yang harus dilakukan robot?\n//    - batasan ukuran, berat, biaya\n// 2. Perancangan mekanik\n//    - rangka, motor, roda, blade\n// 3. Perancangan sensor dan aktuator\n//    - sensor apa, aktuator apa\n// 4. Perancangan sistem kendali\n//    - arsitektur, algoritma, umpan balik\n// 5. Strategi perilaku\n//    - mesin state, prioritas, keamanan\n// 6. Verifikasi dan pengujian\n//    - bagaimana menguji dan mengukur\n\nfunction kerangkaJawabanDesainRobot() {\n    return [\n        \'Spesifikasi kebutuhan\',\n        \'Perancangan mekanik\',\n        \'Perancangan sensor dan aktuator\',\n        \'Perancangan sistem kendali\',\n        \'Strategi perilaku\',\n        \'Verifikasi dan pengujian\'\n    ];\n}',
                        '```',
                        '---',
                        '### Alokasi Waktu UTS',
                        'skill:30%:Bagian tertulis konsep dasar:36 menit',
                        'skill:40%:Bagian desain robot dan kendali:48 menit',
                        'skill:30%:Bagian analisis dan trade-off:36 menit',
                        '---',
                        '### 3 Konsep Inti UTS',
                        'card:UTS Menguji Pemahaman:Soal tidak akan meminta Anda menghafal sintaksis, tetapi menjelaskan mengapa dan kapan menggunakan suatu teknik.',
                        'card:Desain adalah Kunci:Separuh nilai UTS bergantung pada kemampuan Anda merancang robot dan sistem kendalinya.',
                        'card:Integrasi adalah Tujuan:Materi P2–P6 bukan potongan terpisah. UTS menguji kemampuan Anda merangkainya menjadi desain robot yang koheren.',
                        '---',
                        '### Target Kompetensi UTS',
                        'skill:100%:Menjelaskan konsep dasar robotika:Wajib',
                        'skill:100%:Merancang robot sumo sederhana:Wajib',
                        'skill:95%:Memilih sensor dan aktuator:Wajib',
                        'skill:90%:Merancang sistem kendali:Wajib',
                        '---',
                        '### Aktivitas UTS',
                        'table:[{"Aktivitas": "Bagian tertulis", "Deskripsi": "Soal konsep dan analisis, dikerjakan tanpa komputer"}, {"Aktivitas": "Bagian desain", "Deskripsi": "Rancang robot sumo untuk skenario yang diberikan"}, {"Aktivitas": "Bagian kode", "Deskripsi": "Implementasikan loop kendali sederhana dalam JavaScript"}, {"Aktivitas": "Pengumpulan", "Deskripsi": "Kumpulkan jawaban tertulis dan diagram melalui repositori masing-masing"}]',
                        '---',
                    ],
                },
            ],
        },
        {
            name: 'Bagian 3: Kinematika, Pemrograman, dan Visi',
            items: [
                {
                    id: 'modul09',
                    title: 'Pertemuan 9: Active Force Control',
                    lines: [
                        '**Pertemuan 9: Active Force Control**',
                        '*Mengendalikan posisi saja tidak cukup. Robot yang baik juga mengendalikan gaya yang ia berikan ke dunia.*',
                        '---',
                        'Pertemuan ini membuka Bagian 3 dengan membahas Active Force Control (AFC): teknik kendali yang mengatur gaya yang diberikan robot, bukan hanya posisi atau kecepatannya. Anda akan mempelajari konsep, implementasi, dan aplikasinya pada robot sumo.',
                        'Materi ini adalah inti CPL-8 dan menjadi fondasi untuk kinematika dan dinamika robot di pertemuan berikutnya.',
                        '---',
                        '### Mengapa Active Force Control Penting?',
                        'card:Gaya Menentukan Interaksi:Ketika robot sumo mendorong lawan, yang menentukan hasil bukan posisi, melainkan gaya. Mengendalikan gaya berarti mengendalikan hasil pertandingan.',
                        'card:AFC Mengatasi Gangguan:AFC dirancang untuk mengatasi gangguan eksternal seperti tabrakan atau perubahan beban. Ia adalah teknik yang tangguh di lingkungan nyata.',
                        'card:AFC Melengkapi PID:PID mengendalikan posisi dan kecepatan. AFC melengkapinya dengan kendali gaya. Bersama, keduanya membentuk sistem kendali yang lengkap.',
                        '---',
                        '### Konsep Active Force Control',
                        'AFC bekerja dengan mengukur gaya aktual yang diberikan robot, membandingkannya dengan gaya target, dan menyesuaikan output aktuator untuk meminimalkan selisihnya.',
                        '```javascript',
                        '// Active Force Control sederhana\nclass ActiveForceControl {\n    constructor(gayaTarget, Kp = 1.2) {\n        this.gayaTarget = gayaTarget;\n        this.Kp = Kp;\n        this.errorSebelumnya = 0;\n    }\n\n    hitung(gayaAktual) {\n        const error = this.gayaTarget - gayaAktual;\n        const output = this.Kp * error;\n        this.errorSebelumnya = error;\n        return Math.min(255, Math.max(-255, output));\n    }\n\n    // Estimasi gaya dari arus motor\n    estimasiGaya(arus, konstanta = 0.5) {\n        return arus * konstanta;\n    }\n}\n\nconst afc = new ActiveForceControl(50);\nconsole.log(\'Output AFC:\', afc.hitung(40).toFixed(2));\nconsole.log(\'Estimasi gaya:\', afc.estimasiGaya(0.8).toFixed(2), \'N\');',
                        '```',
                        '---',
                        '### Aplikasi AFC pada Robot Sumo',
                        'Pada robot sumo, AFC digunakan untuk memastikan dorongan ke lawan tetap konsisten meskipun ada variasi gesekan, berat lawan, atau kondisi arena.',
                        '```javascript',
                        '// Strategi dorong dengan AFC\nclass StrategiDorong {\n    constructor(afc) {\n        this.afc = afc;\n        this.gayaMaksimal = 100;\n    }\n\n    dorong(gayaLawan) {\n        // Sesuaikan output berdasarkan gaya lawan\n        const gayaTarget = Math.min(this.gayaMaksimal, gayaLawan + 20);\n        this.afc.gayaTarget = gayaTarget;\n        const output = this.afc.hitung(gayaLawan);\n        console.log(\'Dorong dengan output:\', output.toFixed(2));\n        return output;\n    }\n}\n\nconst strategi = new StrategiDorong(afc);\nstrategi.dorong(30);\nstrategi.dorong(60);\nstrategi.dorong(80);',
                        '```',
                        '---',
                        '### AFC vs PID',
                        'AFC dan PID memiliki fokus yang berbeda. Memahami perbedaannya membantu Anda memilih teknik yang tepat untuk setiap situasi.',
                        'table:[{"Aspek": "Fokus", "AFC": "Gaya interaksi", "PID": "Posisi dan kecepatan"}, {"Aspek": "Sensor", "AFC": "Sensor gaya atau arus", "PID": "Encoder atau IMU"}, {"Aspek": "Aplikasi", "AFC": "Dorong, pegang, potong", "PID": "Navigasi, stabilisasi"}, {"Aspek": "Kelebihan", "AFC": "Tangguh terhadap gangguan", "PID": "Sederhana dan terbukti"}]',
                        '---',
                        '### 3 Konsep Inti Active Force Control',
                        'card:Gaya adalah Interaksi:Di dunia nyata, robot berinteraksi melalui gaya. Mengendalikan gaya berarti mengendalikan interaksi.',
                        'card:AFC Melengkapi PID:PID mengendalikan posisi dan kecepatan. AFC melengkapinya dengan kendali gaya. Bersama, keduanya membentuk sistem kendali yang lengkap.',
                        'card:AFC Tangguh terhadap Gangguan:AFC dirancang untuk mengatasi gangguan eksternal seperti tabrakan atau perubahan beban. Ia adalah teknik yang tangguh di lingkungan nyata.',
                        '---',
                        '### Target Kompetensi Pertemuan 9',
                        'skill:100%:Menjelaskan konsep Active Force Control:Wajib',
                        'skill:95%:Mengimplementasikan AFC sederhana:Wajib',
                        'skill:90%:Menerapkan AFC pada strategi dorong robot sumo:Wajib',
                        'skill:85%:Membandingkan AFC dan PID:Pengayaan',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "AFC dasar", "Deskripsi": "Implementasikan kelas ActiveForceControl, uji dengan berbagai gaya aktual"}, {"Aktivitas": "Estimasi gaya", "Deskripsi": "Estimasi gaya dari arus motor, kalibrasi konstanta"}, {"Aktivitas": "Strategi dorong", "Deskripsi": "Implementasikan strategi dorong dengan AFC, uji pada robot sumo"}, {"Aktivitas": "Dokumentasi", "Deskripsi": "Dokumentasikan implementasi AFC di README repo robo-lab"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul10',
                    title: 'Pertemuan 10: Forward dan Inverse Kinematics',
                    lines: [
                        '**Pertemuan 10: Forward dan Inverse Kinematics**',
                        '*Kinematika adalah bahasa gerak robot. Ia menghubungkan sudut motor dengan posisi ujung robot di ruang.*',
                        '---',
                        'Pertemuan ini membahas forward dan inverse kinematics, forward dan inverse dynamic, serta analisis kinematik sistem holonomic dan non-holonomic. Anda akan mempelajari bagaimana menghitung posisi robot dari input motor, dan sebaliknya.',
                        'Materi ini adalah inti CPL-9 dan menjadi fondasi untuk navigasi dan kontrol robot yang presisi.',
                        '---',
                        '### Mengapa Kinematika Penting?',
                        'card:Kinematika Menghubungkan Input dan Output:Kinematika menghubungkan sudut motor (input) dengan posisi robot (output). Tanpa kinematika, robot tidak bisa tahu di mana ia berada.',
                        'card:Holonomic vs Non-holonomic Menentukan Manuver:Robot holonomic bisa bergerak ke segala arah. Robot non-holonomic seperti robot sumo memiliki batasan gerak yang harus dipahami.',
                        'card:Dinamika Melengkapi Kinematika:Kinematika hanya membahas gerak tanpa memperhitungkan gaya. Dinamika melengkapinya dengan memperhitungkan massa, inersia, dan gaya.',
                        '---',
                        '### Forward Kinematics',
                        'Forward kinematics menghitung posisi akhir robot berdasarkan kecepatan roda dan waktu. Ini adalah perhitungan dasar untuk odometri.',
                        '```javascript',
                        '// Forward kinematics robot diferensial\nclass ForwardKinematics {\n    constructor(jarakRoda) {\n        this.jarakRoda = jarakRoda;\n        this.x = 0;\n        this.y = 0;\n        this.theta = 0;\n    }\n\n    update(vKiri, vKanan, dt) {\n        const v = (vKiri + vKanan) / 2;\n        const omega = (vKanan - vKiri) / this.jarakRoda;\n        this.x += v * Math.cos(this.theta) * dt;\n        this.y += v * Math.sin(this.theta) * dt;\n        this.theta += omega * dt;\n        return { x: this.x, y: this.y, theta: this.theta };\n    }\n}\n\nconst fk = new ForwardKinematics(0.15);\nconsole.log(\'Posisi awal:\', fk.update(0.5, 0.5, 1));\nconsole.log(\'Setelah 1 detik:\', fk.update(0.5, 0.5, 1));\nconsole.log(\'Setelah berputar:\', fk.update(0.3, 0.7, 1));',
                        '```',
                        '---',
                        '### Inverse Kinematics',
                        'Inverse kinematics melakukan kebalikannya: menghitung kecepatan roda yang diperlukan untuk mencapai posisi atau kecepatan target.',
                        '```javascript',
                        '// Inverse kinematics robot diferensial\nclass InverseKinematics {\n    constructor(jarakRoda) {\n        this.jarakRoda = jarakRoda;\n    }\n\n    hitungRoda(vTarget, omegaTarget) {\n        const vKiri = vTarget - (omegaTarget * this.jarakRoda) / 2;\n        const vKanan = vTarget + (omegaTarget * this.jarakRoda) / 2;\n        return { kiri: vKiri, kanan: vKanan };\n    }\n\n    // Ke posisi target\n    kePosisi(xTarget, yTarget, xAwal, yAwal, thetaAwal) {\n        const dx = xTarget - xAwal;\n        const dy = yTarget - yAwal;\n        const jarak = Math.hypot(dx, dy);\n        const sudutTarget = Math.atan2(dy, dx);\n        const deltaTheta = sudutTarget - thetaAwal;\n        return { jarak, deltaTheta };\n    }\n}\n\nconst ik = new InverseKinematics(0.15);\nconsole.log(\'Roda:\', ik.hitungRoda(0.5, 1.0));\nconsole.log(\'Ke posisi:\', ik.kePosisi(1, 1, 0, 0, 0));',
                        '```',
                        '---',
                        '### Holonomic vs Non-holonomic',
                        'Robot holonomic dapat bergerak ke segala arah tanpa batasan. Robot non-holonomic seperti robot sumo memiliki batasan karena hanya bisa bergerak maju/mundur dan berputar.',
                        'table:[{"Aspek": "Holonomic", "Non-holonomic": "Non-holonomic"}, {"Kebebasan": "Holonomic": "3 DOF (x, y, theta)", "Non-holonomic": "2 DOF (v, omega)"}, {"Contoh": "Holonomic": "Robot mecanum, drone", "Non-holonomic": "Robot sumo, mobil"}, {"Keunggulan": "Holonomic": "Manuver fleksibel", "Non-holonomic": "Struktur sederhana"}, {"Keterbatasan": "Holonomic": "Kompleks, mahal", "Non-holonomic": "Tidak bisa bergerak lateral"}]',
                        '---',
                        '### 3 Konsep Inti Kinematika',
                        'card:Kinematika adalah Bahasa Gerak:Kinematika menghubungkan input motor dengan output gerak. Tanpa kinematika, robot tidak bisa tahu di mana ia berada.',
                        'card:Forward dan Inverse Saling Melengkapi:Forward kinematics menghitung posisi dari kecepatan roda. Inverse kinematics menghitung kecepatan roda dari posisi target.',
                        'card:Holonomic vs Non-holonomic Menentukan Manuver:Robot holonomic bisa bergerak ke segala arah. Robot non-holonomic seperti robot sumo memiliki batasan gerak yang harus dipahami.',
                        '---',
                        '### Target Kompetensi Pertemuan 10',
                        'skill:100%:Menerapkan forward kinematics:Wajib',
                        'skill:95%:Menerapkan inverse kinematics:Wajib',
                        'skill:90%:Membedakan sistem holonomic dan non-holonomic:Wajib',
                        'skill:85%:Menerapkan dinamika sederhana:Pengayaan',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Forward kinematics", "Deskripsi": "Implementasikan forward kinematics, uji dengan berbagai kecepatan roda"}, {"Aktivitas": "Inverse kinematics", "Deskripsi": "Implementasikan inverse kinematics, uji dengan target posisi"}, {"Aktivitas": "Odometri", "Deskripsi": "Gunakan forward kinematics untuk odometri, bandingkan dengan posisi aktual"}, {"Aktivitas": "Dokumentasi", "Deskripsi": "Dokumentasikan kinematika robot sumo di README repo robo-lab"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul11',
                    title: 'Pertemuan 11: Alat Pemrograman Robot',
                    lines: [
                        '**Pertemuan 11: Alat Pemrograman Robot**',
                        '*Robot yang cerdas lahir dari kode yang baik. Alat pemrograman adalah pena dan kertas programmer robot.*',
                        '---',
                        'Pertemuan ini membahas alat pemrograman robot: bahasa pemrograman, framework, simulator, dan alat pengembangan. Anda akan mempelajari cara memilih dan menggunakan alat yang tepat untuk proyek RoboLab.',
                        'Materi ini adalah inti CPL-10 dan menjadi fondasi untuk implementasi firmware dan aplikasi kontroler di pertemuan berikutnya.',
                        '---',
                        '### Mengapa Alat Pemrograman Penting?',
                        'card:Alat Menentukan Produktivitas:Alat yang tepat membuat pengembangan lebih cepat, debugging lebih mudah, dan hasil lebih baik. Alat yang salah membuang waktu dan tenaga.',
                        'card:Simulator Menghemat Biaya:Simulator memungkinkan pengujian tanpa perangkat keras. Ini menghemat biaya, waktu, dan risiko kerusakan.',
                        'card:Firmware adalah Nyawa Robot:Firmware adalah program yang berjalan di mikrokontroler. Kualitas firmware menentukan perilaku robot.',
                        '---',
                        '### Bahasa Pemrograman untuk Robotika',
                        'Robotika mendukung berbagai bahasa pemrograman, masing-masing dengan kelebihan dan kegunaannya. Untuk RoboLab, kita memakai JavaScript (web), Arduino C++ (firmware), dan Python (analisis).',
                        '```javascript',
                        '// Perbandingan bahasa untuk robotika\nconst BAHASA_ROBOTIKA = {\n    arduino: {\n        kegunaan: \'Firmware mikrokontroler\',\n        kelebihan: \'Akses langsung ke hardware, ringan\',\n        contoh: \'ESP32, Arduino Uno, STM32\'\n    },\n    javascript: {\n        kegunaan: \'Aplikasi web kontroler\',\n        kelebihan: \'Cross-platform, mudah diakses\',\n        contoh: \'WebSocket, WebRTC, Canvas\'\n    },\n    python: {\n        kegunaan: \'Analisis, prototipe, machine learning\',\n        kelebihan: \'Ekstensif, mudah dibaca\',\n        contoh: \'ROS, OpenCV, NumPy\'\n    },\n    cpp: {\n        kegunaan: \'Sistem real-time, ROS\',\n        kelebihan: \'Cepat, kontrol penuh\',\n        contoh: \'ROS 2, embedded system\'\n    }\n};\n\nfor (const [bahasa, info] of Object.entries(BAHASA_ROBOTIKA)) {\n    console.log(bahasa.toUpperCase(), \'→\', info.kegunaan);\n}',
                        '```',
                        '---',
                        '### Firmware ESP32 dengan Arduino IDE',
                        'Firmware RoboLab berjalan di ESP32 dan bertanggung jawab atas pembacaan sensor, kontrol motor, dan komunikasi WiFi dengan aplikasi web kontroler.',
                        '```javascript',
                        '// Firmware ESP32 — kerangka dasar\n#include <WiFi.h>\n#include <WebServer.h>\n\nconst char* ssid = "RoboLab";\nconst char* password = "password123";\n\nWebServer server(80);\n\n// Pin motor\nconst int motorKiriMaju = 12;\nconst int motorKiriMundur = 13;\nconst int motorKananMaju = 25;\nconst int motorKananMundur = 26;\n\nvoid setup() {\n    Serial.begin(115200);\n    pinMode(motorKiriMaju, OUTPUT);\n    pinMode(motorKiriMundur, OUTPUT);\n    pinMode(motorKananMaju, OUTPUT);\n    pinMode(motorKananMundur, OUTPUT);\n    \n    WiFi.begin(ssid, password);\n    while (WiFi.status() != WL_CONNECTED) {\n        delay(500);\n    }\n    Serial.println("WiFi terhubung!");\n    \n    server.on("/maju", []() {\n        digitalWrite(motorKiriMaju, HIGH);\n        digitalWrite(motorKananMaju, HIGH);\n        server.send(200, "text/plain", "Maju");\n    });\n    \n    server.begin();\n}\n\nvoid loop() {\n    server.handleClient();\n}',
                        '```',
                        '---',
                        '### Alat Pengembangan dan Simulator',
                        'Selain bahasa pemrograman, ada berbagai alat yang mempercepat pengembangan robot. Berikut alat yang akan dipakai di RoboLab.',
                        'table:[{"Alat": "Arduino IDE", "Kegunaan": "Menulis dan upload firmware", "Catatan": "Mendukung ESP32 via board manager"}, {"Alat": "PlatformIO", "Kegunaan": "Alternatif Arduino IDE", "Catatan": "Lebih baik untuk proyek besar"}, {"Alat": "Wokwi", "Kegunaan": "Simulator ESP32 online", "Catatan": "Uji firmware tanpa hardware"}, {"Alat": "WebSocket Client", "Kegunaan": "Uji komunikasi WiFi", "Catatan": "Browser atau aplikasi khusus"}]',
                        '---',
                        '### 3 Konsep Inti Alat Pemrograman',
                        'card:Alat Menentukan Produktivitas:Alat yang tepat membuat pengembangan lebih cepat, debugging lebih mudah, dan hasil lebih baik. Pilih alat sesuai kebutuhan, bukan karena tren.',
                        'card:Firmware adalah Nyawa Robot:Firmware adalah program yang berjalan di mikrokontroler. Kualitas firmware menentukan perilaku robot.',
                        'card:Simulator Menghemat Biaya:Simulator memungkinkan pengujian tanpa perangkat keras. Ini menghemat biaya, waktu, dan risiko kerusakan.',
                        '---',
                        '### Target Kompetensi Pertemuan 11',
                        'skill:100%:Memilih bahasa pemrograman yang tepat:Wajib',
                        'skill:95%:Menulis firmware dasar ESP32:Wajib',
                        'skill:90%:Menggunakan simulator untuk pengujian:Wajib',
                        'skill:85%:Mengintegrasikan firmware dengan aplikasi web:Pengayaan',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Firmware dasar", "Deskripsi": "Tulis firmware ESP32 yang menyalakan LED melalui WiFi"}, {"Aktivitas": "Kontrol motor", "Deskripsi": "Tambahkan kontrol motor ke firmware, uji via HTTP request"}, {"Aktivitas": "Simulator", "Deskripsi": "Uji firmware di Wokwi atau simulator lain sebelum upload ke ESP32"}, {"Aktivitas": "Dokumentasi", "Deskripsi": "Dokumentasikan firmware dan alat yang dipakai di README repo robo-lab"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul12',
                    title: 'Pertemuan 12: Mobile Robot dan Sensor',
                    lines: [
                        '**Pertemuan 12: Mobile Robot dan Sensor**',
                        '*Mobile robot adalah robot yang berpindah tempat. Kemampuan navigasi adalah yang membedakannya dari robot industri yang diam.*',
                        '---',
                        'Pertemuan ini membahas mobile robot dan kategori sensor yang digunakan. Anda akan mempelajari navigasi, lokalisasi, pemetaan, dan sensor-sensor yang mendukung mobile robot — termasuk robot sumo RoboLab.',
                        'Materi ini adalah inti CPL-11 dan menjadi fondasi untuk navigasi otonom robot sumo.',
                        '---',
                        '### Mengapa Mobile Robot Penting?',
                        'card:Mobile Robot Menjelajah Dunia:Mobile robot bergerak di lingkungan nyata — pabrik, gudang, rumah, jalan. Kemampuan navigasi adalah inti dari kegunaannya.',
                        'card:Sensor adalah Kunci Navigasi:Navigasi memerlukan sensor untuk merasakan lingkungan. Berbagai sensor digunakan bersama untuk membangun peta dan menentukan posisi.',
                        'card:Robot Sumo adalah Mobile Robot:Robot sumo RoboLab adalah mobile robot dengan misi khusus: mendorong lawan keluar arena. Prinsip navigasinya sama dengan mobile robot lain.',
                        '---',
                        '### Kategori Sensor Mobile Robot',
                        'Mobile robot menggunakan berbagai sensor untuk navigasi. Kategori utama: sensor proprioceptive (internal) dan exteroceptive (eksternal).',
                        '```javascript',
                        '// Kategori sensor mobile robot\nconst SENSOR_MOBILE = {\n    proprioceptive: {\n        deskripsi: \'Mengukur state internal robot\',\n        contoh: [\'Encoder roda\', \'IMU\', \'Gyroscope\', \'Akselerometer\']\n    },\n    exteroceptive: {\n        deskripsi: \'Mengukur lingkungan eksternal\',\n        contoh: [\'Ultrasonik\', \'Lidar\', \'Kamera\', \'Inframerah\']\n    },\n    navigasi: {\n        deskripsi: \'Mendukung navigasi dan lokalisasi\',\n        contoh: [\'GPS\', \'Kompas\', \'Lidar SLAM\']\n    }\n};\n\nfor (const [kategori, info] of Object.entries(SENSOR_MOBILE)) {\n    console.log(kategori.toUpperCase(), \'→\', info.contoh.join(\', \'));\n}',
                        '```',
                        '---',
                        '### Navigasi dan Lokalisasi',
                        'Navigasi adalah proses menentukan jalur dari posisi saat ini ke posisi target. Lokalisasi adalah proses menentukan posisi saat ini. Keduanya saling terkait.',
                        '```javascript',
                        '// Navigasi sederhana dengan sensor\nclass NavigasiRobot {\n    constructor() {\n        this.posisi = { x: 0, y: 0, theta: 0 };\n        this.target = { x: 0, y: 0 };\n    }\n\n    setTarget(x, y) {\n        this.target = { x, y };\n    }\n\n    hitungArah() {\n        const dx = this.target.x - this.posisi.x;\n        const dy = this.target.y - this.posisi.y;\n        return Math.atan2(dy, dx);\n    }\n\n    hitungJarak() {\n        const dx = this.target.x - this.posisi.x;\n        const dy = this.target.y - this.posisi.y;\n        return Math.hypot(dx, dy);\n    }\n\n    update(deltaX, deltaY, deltaTheta) {\n        this.posisi.x += deltaX;\n        this.posisi.y += deltaY;\n        this.posisi.theta += deltaTheta;\n    }\n}\n\nconst nav = new NavigasiRobot();\nnav.setTarget(5, 5);\nconsole.log(\'Arah:\', nav.hitungArah().toFixed(2), \'rad\');\nconsole.log(\'Jarak:\', nav.hitungJarak().toFixed(2), \'m\');',
                        '```',
                        '---',
                        '### Navigasi Robot Sumo',
                        'Robot sumo memiliki misi navigasi khusus: mencari lawan, mendorongnya keluar, dan menghindari garis arena. Strategi ini menggabungkan navigasi reaktif dan perilaku berbasis state.',
                        'table:[{"Perilaku": "Cari lawan", "Sensor": "Ultrasonik", "Aksi": "Berputar mencari sinyal"}, {"Perilaku": "Serang", "Sensor": "Ultrasonik + IMU", "Aksi": "Maju cepat ke arah lawan"}, {"Perilaku": "Hindari garis", "Sensor": "Inframerah", "Aksi": "Mundur dan berputar"}, {"Perilaku": "Bertahan", "Sensor": "Semua", "Aksi": "Berputar cepat di tempat"}]',
                        '---',
                        '### 3 Konsep Inti Mobile Robot',
                        'card:Navigasi adalah Inti:Navigasi memungkinkan robot berpindah dari satu tempat ke tempat lain. Ia adalah inti dari mobile robot.',
                        'card:Sensor adalah Indra:Mobile robot menggunakan berbagai sensor untuk merasakan lingkungan. Kombinasi sensor menghasilkan pemahaman yang lebih kaya.',
                        'card:Robot Sumo adalah Mobile Robot:Robot sumo RoboLab adalah mobile robot dengan misi khusus. Prinsip navigasinya sama dengan mobile robot lain.',
                        '---',
                        '### Target Kompetensi Pertemuan 12',
                        'skill:100%:Menjelaskan kategori sensor mobile robot:Wajib',
                        'skill:95%:Menerapkan navigasi sederhana:Wajib',
                        'skill:90%:Merancang perilaku navigasi robot sumo:Wajib',
                        'skill:85%:Mengintegrasikan sensor untuk lokalisasi:Pengayaan',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Navigasi dasar", "Deskripsi": "Implementasikan navigasi sederhana ke target posisi"}, {"Aktivitas": "Perilaku robot sumo", "Deskripsi": "Implementasikan perilaku cari lawan, serang, hindari garis"}, {"Aktivitas": "Integrasi sensor", "Deskripsi": "Gabungkan ultrasonik dan inframerah untuk navigasi robot sumo"}, {"Aktivitas": "Uji di arena", "Deskripsi": "Uji navigasi robot sumo di arena mini, catat keberhasilan"}]',
                        '---',
                    ],
                },
            ],
        },

                {
            name: 'Bagian 4: Visi, Perancangan, dan Evaluasi Akhir',
            items: [
                {
                    id: 'modul13',
                    title: 'Pertemuan 13: Robot Vision',
                    lines: [
                        '**Pertemuan 13: Robot Vision**',
                        '*Mata adalah indra paling kaya. Robot yang bisa melihat memiliki pemahaman dunia yang jauh lebih dalam.*',
                        '---',
                        'Pertemuan ini membahas robot vision: formasi citra dan sensor image. Anda akan mempelajari bagaimana robot menangkap, memproses, dan memahami citra untuk mengambil keputusan.',
                        'Materi ini adalah inti CPL-12 dan menghubungkan Robotika dengan Computer Vision yang sudah Anda pelajari. Robot sumo RoboLab dapat memanfaatkan visi untuk mendeteksi lawan dan garis dengan lebih akurat.',
                        '---',
                        '### Mengapa Robot Vision Penting?',
                        'card:Visi Memberi Informasi Kaya:Sensor ultrasonik hanya memberi jarak. Kamera memberi warna, bentuk, tekstur, dan gerakan. Visi adalah indra paling kaya untuk robot.',
                        'card:Visi Menghubungkan Robotika dan CV:Robot vision adalah jembatan antara robotika dan computer vision. Ia memungkinkan robot memahami dunia seperti manusia.',
                        'card:Visi Membuka Aplikasi Baru:Navigasi visual, pengenalan objek, dan visual servoing adalah aplikasi robot vision yang terus berkembang.',
                        '---',
                        '### Formasi Citra pada Robot',
                        'Robot menangkap citra melalui kamera. Citra yang ditangkap direpresentasikan sebagai matriks piksel yang bisa diproses untuk ekstraksi informasi.',
                        '```javascript',
                        '// Formasi citra dan pemrosesan dasar\nclass KameraRobot {\n    constructor(lebar, tinggi) {\n        this.lebar = lebar;\n        this.tinggi = tinggi;\n    }\n\n    // Simulasi tangkap citra\n    tangkapCitra() {\n        const citra = [];\n        for (let y = 0; y < this.tinggi; y++) {\n            const baris = [];\n            for (let x = 0; x < this.lebar; x++) {\n                baris.push({\n                    r: Math.floor(Math.random() * 256),\n                    g: Math.floor(Math.random() * 256),\n                    b: Math.floor(Math.random() * 256)\n                });\n            }\n            citra.push(baris);\n        }\n        return citra;\n    }\n\n    // Deteksi area terang (simulasi deteksi lawan)\n    deteksiAreaTerang(citra, ambang = 200) {\n        let jumlah = 0;\n        for (const baris of citra) {\n            for (const piksel of baris) {\n                const kecerahan = (piksel.r + piksel.g + piksel.b) / 3;\n                if (kecerahan > ambang) jumlah++;\n            }\n        }\n        return jumlah;\n    }\n}\n\nconst kamera = new KameraRobot(160, 120);\nconst citra = kamera.tangkapCitra();\nconsole.log(\'Area terang:\', kamera.deteksiAreaTerang(citra), \'piksel\');',
                        '```',
                        '---',
                        '### Sensor Image dan Pemrosesan',
                        'Sensor image pada robot dapat berupa kamera RGB, kamera depth, atau sensor inframerah. Setiap sensor memiliki karakteristik dan kegunaan yang berbeda.',
                        '```javascript',
                        '// Pemrosesan citra untuk deteksi lawan\nclass DeteksiLawanVisual {\n    constructor(ambangWarna) {\n        this.ambangWarna = ambangWarna;\n    }\n\n    // Deteksi warna tertentu dalam citra\n    deteksiWarna(citra, warnaTarget) {\n        let jumlah = 0;\n        let sumX = 0, sumY = 0;\n        for (let y = 0; y < citra.length; y++) {\n            for (let x = 0; x < citra[y].length; x++) {\n                const p = citra[y][x];\n                const jarak = Math.hypot(p.r - warnaTarget.r, p.g - warnaTarget.g, p.b - warnaTarget.b);\n                if (jarak < this.ambangWarna) {\n                    jumlah++;\n                    sumX += x;\n                    sumY += y;\n                }\n            }\n        }\n        if (jumlah === 0) return null;\n        return { x: sumX / jumlah, y: sumY / jumlah, jumlah };\n    }\n}\n\nconst detektor = new DeteksiLawanVisual(50);\nconst posisiLawan = detektor.deteksiWarna(citra, { r: 255, g: 0, b: 0 });\nconsole.log(\'Posisi lawan:\', posisiLawan ? `(${posisiLawan.x.toFixed(1)}, ${posisiLawan.y.toFixed(1)})` : \'tidak terdeteksi\');',
                        '```',
                        '---',
                        '### Aplikasi Robot Vision',
                        'Robot vision memiliki banyak aplikasi, dari navigasi hingga manipulasi objek. Berikut beberapa yang paling umum.',
                        'table:[{"Aplikasi": "Deteksi lawan", "Sensor": "Kamera RGB", "Kegunaan": "Robot sumo, robot pertandingan"}, {"Aplikasi": "Navigasi visual", "Sensor": "Kamera + IMU", "Kegunaan": "Mobile robot otonom"}, {"Aplikasi": "Pengenalan objek", "Sensor": "Kamera + deep learning", "Kegunaan": "Robot layanan, industri"}, {"Aplikasi": "Visual servoing", "Sensor": "Kamera + encoder", "Kegunaan": "Manipulasi presisi"}]',
                        '---',
                        '### 3 Konsep Inti Robot Vision',
                        'card:Visi adalah Indra Kaya:Visi memberi robot informasi yang jauh lebih kaya daripada sensor tunggal. Warna, bentuk, tekstur, dan gerakan semuanya bisa ditangkap.',
                        'card:Formasi Citra adalah Fondasi:Memahami bagaimana citra terbentuk adalah fondasi robot vision. Tanpa pemahaman ini, pemrosesan citra menjadi tebak-tebakan.',
                        'card:Visi Membuka Aplikasi Baru:Navigasi visual, pengenalan objek, dan visual servoing adalah aplikasi robot vision yang terus berkembang.',
                        '---',
                        '### Target Kompetensi Pertemuan 13',
                        'skill:100%:Menjelaskan formasi citra pada robot:Wajib',
                        'skill:95%:Memproses citra untuk deteksi objek:Wajib',
                        'skill:90%:Menerapkan robot vision pada robot sumo:Wajib',
                        'skill:85%:Mengintegrasikan visi dengan sensor lain:Pengayaan',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Formasi citra", "Deskripsi": "Tangkap citra dari kamera, tampilkan dalam canvas, analisis distribusi warna"}, {"Aktivitas": "Deteksi warna", "Deskripsi": "Deteksi objek berwarna dalam citra, hitung posisi pusatnya"}, {"Aktivitas": "Integrasi visi", "Deskripsi": "Integrasikan deteksi visual dengan sensor ultrasonik untuk robot sumo"}, {"Aktivitas": "Dokumentasi", "Deskripsi": "Dokumentasikan sistem robot vision di README repo robo-lab"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul14',
                    title: 'Pertemuan 14: Perancangan dan Pembuatan Robot',
                    lines: [
                        '**Pertemuan 14: Perancangan dan Pembuatan Robot**',
                        '*Teori menjadi bermakna ketika ia diwujudkan dalam karya. Inilah saatnya membangun robot sumo yang utuh.*',
                        '---',
                        'Pertemuan ini adalah praktikum perancangan dan pembuatan robot. Anda akan mengintegrasikan mekanik, elektronik, dan kendali menjadi robot sumo RoboLab yang utuh dan berfungsi.',
                        'Materi ini adalah inti CPL-13 dan menjadi bekal untuk Final Review dan UAS.',
                        '---',
                        '### Mengapa Perancangan dan Pembuatan Robot Penting?',
                        'card:Integrasi adalah Tujuan:Akhir dari pembelajaran robotika adalah kemampuan membangun robot lengkap yang berfungsi. Ini adalah puncak dari semua yang telah dipelajari.',
                        'card:Kerja Tim adalah Realitas:Proyek robotika dikerjakan dalam tim. Proyek akhir melatih Anda berkolaborasi, berbagi tanggung jawab, dan berkomunikasi.',
                        'card:Portofolio adalah Aset:Robot sumo yang berfungsi adalah portofolio yang bisa Anda tunjukkan. Ia adalah bukti nyata kemampuan Anda.',
                        '---',
                        '### Struktur Proyek RoboLab',
                        'Proyek RoboLab memiliki struktur direktori yang terorganisir. Setiap folder memiliki tanggung jawab yang jelas.',
                        '```javascript',
                        '// Struktur proyek robo-lab\n// robo-lab/\n// ├── firmware/        # Kode ESP32 (ino)\n// │   ├── main.ino\n// │   ├── motor.h\n// │   └── sensor.h\n// ├── web/             # Aplikasi kontroler\n// │   ├── index.html\n// │   ├── style.css\n// │   └── app.js\n// ├── hardware/        # Desain mekanik dan skema\n// │   ├── rangka.stl\n// │   └── skema.fzz\n// ├── docs/            # Dokumentasi\n// ├── test/            # Uji firmware\n// └── README.md\n\nconst STRUKTUR_ROBOLAB = {\n    firmware: [\'main.ino\', \'motor.h\', \'sensor.h\', \'wifi.h\'],\n    web: [\'index.html\', \'style.css\', \'app.js\', \'websocket.js\'],\n    hardware: [\'rangka\', \'skema elektronik\', \'daftar komponen\'],\n    docs: [\'spesifikasi\', \'panduan perakitan\', \'panduan penggunaan\']\n};\n\nconsole.log(\'Struktur robo-lab siap dibangun\');',
                        '```',
                        '---',
                        '### Integrasi Mekanik, Elektronik, dan Kendali',
                        'Robot sumo yang berfungsi adalah hasil integrasi tiga komponen: mekanik yang kokoh, elektronik yang andal, dan kendali yang cerdas.',
                        '```javascript',
                        '// Integrasi sistem robot sumo\nclass RobotSumo {\n    constructor(nama) {\n        this.nama = nama;\n        this.mekanik = { rangka: null, motor: null, roda: null };\n        this.elektronik = { esp32: null, driver: null, sensor: [] };\n        this.kendali = { mode: \'idle\', strategi: null };\n        this.status = \'belum siap\';\n    }\n\n    pasangMekanik(rangka, motor, roda) {\n        this.mekanik = { rangka, motor, roda };\n        console.log(\'Mekanik terpasang\');\n        this.cekStatus();\n    }\n\n    pasangElektronik(esp32, driver, sensor) {\n        this.elektronik = { esp32, driver, sensor };\n        console.log(\'Elektronik terpasang\');\n        this.cekStatus();\n    }\n\n    setKendali(mode, strategi) {\n        this.kendali = { mode, strategi };\n        console.log(\'Kendali diatur:\', mode);\n        this.cekStatus();\n    }\n\n    cekStatus() {\n        const mekanikSiap = this.mekanik.rangka && this.mekanik.motor;\n        const elektronikSiap = this.elektronik.esp32 && this.elektronik.driver;\n        const kendaliSiap = this.kendali.strategi !== null;\n        this.status = (mekanikSiap && elektronikSiap && kendaliSiap) ? \'siap\' : \'belum siap\';\n        console.log(\'Status:\', this.status);\n    }\n}\n\nconst robot = new RobotSumo(\'RoboLab-01\');\nrobot.pasangMekanik(\'akrilik\', \'DC gearbox\', \'karet\');\nrobot.pasangElektronik(\'ESP32\', \'L298N\', [\'ultrasonik\', \'inframerah\']);\nrobot.setKendali(\'otonom\', \'state-machine\');',
                        '```',
                        '---',
                        '### Tahapan Pembuatan Robot',
                        'Pembuatan robot sumo mengikuti tahapan yang sistematis. Setiap tahap memiliki keluaran yang jelas dan kriteria verifikasi.',
                        'table:[{"Tahap": "1. Persiapan", "Kegiatan": "Kumpulkan komponen, siapkan alat", "Keluaran": "Daftar komponen lengkap"}, {"Tahap": "2. Perakitan mekanik", "Kegiatan": "Rakit rangka, pasang motor dan roda", "Keluaran": "Rangka robot siap"}, {"Tahap": "3. Perakitan elektronik", "Kegiatan": "Pasang ESP32, driver, sensor", "Keluaran": "Sistem elektronik terhubung"}, {"Tahap": "4. Firmware", "Kegiatan": "Upload firmware, uji sensor dan motor", "Keluaran": "Firmware berfungsi"}, {"Tahap": "5. Aplikasi web", "Kegiatan": "Bangun antarmuka kontroler", "Keluaran": "Aplikasi web berfungsi"}, {"Tahap": "6. Uji arena", "Kegiatan": "Uji robot di arena, tuning parameter", "Keluaran": "Robot siap bertanding"}]',
                        '---',
                        '### 3 Konsep Inti Perancangan dan Pembuatan',
                        'card:Integrasi adalah Tujuan:Akhir dari pembelajaran robotika adalah kemampuan membangun robot lengkap yang berfungsi. Ini adalah puncak dari semua yang telah dipelajari.',
                        'card:Kerja Tim adalah Realitas:Proyek robotika dikerjakan dalam tim. Proyek akhir melatih Anda berkolaborasi, berbagi tanggung jawab, dan berkomunikasi.',
                        'card:Portofolio adalah Aset:Robot sumo yang berfungsi adalah portofolio yang bisa Anda tunjukkan. Ia adalah bukti nyata kemampuan Anda.',
                        '---',
                        '### Target Kompetensi Pertemuan 14',
                        'skill:100%:Mengintegrasikan mekanik, elektronik, dan kendali:Wajib',
                        'skill:95%:Membangun robot sumo yang berfungsi:Wajib',
                        'skill:90%:Berkolaborasi dalam tim:Wajib',
                        'skill:85%:Mendokumentasikan proyek secara profesional:Wajib',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Perakitan mekanik", "Deskripsi": "Rakit rangka, pasang motor dan roda, uji gerak dasar"}, {"Aktivitas": "Perakitan elektronik", "Deskripsi": "Pasang ESP32, driver motor, dan sensor pada rangka"}, {"Aktivitas": "Upload firmware", "Deskripsi": "Upload firmware ke ESP32, uji komunikasi WiFi dan kontrol motor"}, {"Aktivitas": "Uji di arena", "Deskripsi": "Uji robot sumo di arena mini, catat performa dan perbaiki"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul15',
                    title: 'Pertemuan 15: Final Review dan Demo P9–P14',
                    lines: [
                        '**Pertemuan 15: Final Review dan Demo P9–P14**',
                        '*Perjalanan panjang layak dirayakan — tetapi juga layak diuji. Inilah saatnya menunjukkan apa yang telah Anda bangun.*',
                        '---',
                        'Pertemuan ini adalah final review dan demo proyek. Kita akan mengulang materi P9–P14, meninjau kembali perjalanan semester, dan mempersiapkan demo terpadu untuk UAS.',
                        'Manfaatkan pertemuan ini untuk menyempurnakan robot sumo RoboLab dan memastikan semua artefak siap dinilai.',
                        '---',
                        '### Apa yang Harus Bisa Didemonstrasikan',
                        'card:Robot Berfungsi:Robot sumo harus berfungsi — bergerak, mendeteksi lawan, menghindari garis, dan merespons perintah dari aplikasi web.',
                        'card:Data Terukur:Setiap pengujian harus menghasilkan data — waktu respons, akurasi deteksi, keberhasilan strategi. Demo tanpa data bukan demo, melainkan klaim.',
                        'card:Dokumentasi Lengkap:Repo harus memiliki README, dokumentasi firmware, skema elektronik, dan panduan penggunaan. Dokumentasi adalah bagian dari produk.',
                        '---',
                        '### Rubrik Penilaian Final Review',
                        'table:[{"Komponen": "Fungsionalitas robot", "Bobot": "30%", "Indikator": "Robot berfungsi, semua fitur utama berjalan"}, {"Komponen": "Kualitas firmware dan web", "Bobot": "25%", "Indikator": "Kode bersih, terstruktur, terdokumentasi"}, {"Komponen": "Dokumentasi dan repo", "Bobot": "20%", "Indikator": "README, skema, panduan lengkap"}, {"Komponen": "Presentasi dan demo", "Bobot": "25%", "Indikator": "Demo lancar, penjelasan jelas, tanya jawab memuaskan"}]',
                        '---',
                        '### Kilas Balik Perjalanan Semester',
                        'card:Bagian 1 — Fondasi:Anda belajar definisi, sejarah, jenis robot, perancangan, dan mekanik robot. Ini adalah fondasi yang membuat semua tahap berikutnya mungkin.',
                        'card:Bagian 2 — Sensor dan Kendali:Anda belajar sensor, aktuator, dan sistem kendali. Ini adalah indra dan otot robot.',
                        'card:Bagian 3 — Kinematika, Pemrograman, dan Visi:Anda belajar kinematika, alat pemrograman, mobile robot, dan robot vision. Ini adalah otak dan mata robot.',
                        '---',
                        '### Kriteria Kelulusan',
                        'skill:100%:Robot berfungsi tanpa error:Wajib',
                        'skill:95%:Firmware dan aplikasi web terintegrasi:Wajib',
                        'skill:90%:Dokumentasi lengkap dan rapi:Wajib',
                        'skill:85%:Presentasi jelas dan meyakinkan:Wajib',
                        '---',
                        '### Aktivitas Praktikum',
                        'table:[{"Aktivitas": "Peer review", "Deskripsi": "Review firmware dan rancangan robot kelompok lain, beri masukan konstruktif"}, {"Aktivitas": "Demo internal", "Deskripsi": "Demo robot ke kelompok lain, kumpulkan umpan balik"}, {"Aktivitas": "Perbaikan akhir", "Deskripsi": "Perbaiki bug dan dokumentasi berdasarkan umpan balik"}, {"Aktivitas": "Rilis v1.0", "Deskripsi": "Buat tag v1.0 di repo, arsipkan artefak, siapkan laporan akhir"}]',
                        '---',
                    ],
                },
                {
                    id: 'modul16',
                    title: 'UAS: Demo Terpadu RoboLab',
                    lines: [
                        '**UAS: Demo Terpadu RoboLab**',
                        '*Inilah puncak perjalanan — saatnya menunjukkan bahwa Anda bukan hanya belajar, tetapi membangun.*',
                        '---',
                        'UAS adalah demo terpadu proyek RoboLab. Anda akan mempresentasikan robot sumo yang berfungsi, firmware, aplikasi web kontroler, dan dokumentasi yang Anda bangun sepanjang semester.',
                        'Ujian ini mengevaluasi materi P9–P14 dan kemampuan Anda mengintegrasikan semua yang telah dipelajari.',
                        '---',
                        '### Apa yang Membedakan dari UTS',
                        'card:UAS Menuntut Integrasi:UTS menguji pemahaman konsep. UAS menguji kemampuan merangkai semua konsep menjadi robot yang berfungsi.',
                        'card:UAS Menuntut Bukti:UTS cukup dengan jawaban benar. UAS menuntut bukti — robot yang berjalan, data pengujian, dan performa terukur.',
                        'card:UAS Menuntut Presentasi:UTS dinilai dari lembar jawaban. UAS dinilai dari kemampuan Anda menjelaskan dan mempertahankan karya di depan penguji.',
                        '---',
                        '### Arsitektur RoboLab',
                        '```javascript',
                        '// Arsitektur lengkap RoboLab\n// Aplikasi Web (HTML + CSS + JS)\n//   ↓ WebSocket\n// ESP32 (WiFi)\n//   ↓ GPIO\n// Motor Driver → Motor DC\n//   ↑\n// Sensor (ultrasonik, inframerah, IMU, kamera opsional)\n\nconst ARSITEKTUR_ROBOLAB = {\n    lapisan: [\n        \'Aplikasi web — antarmuka kontroler\',\n        \'Komunikasi — WebSocket via WiFi\',\n        \'Firmware — ESP32 (Arduino)\',\n        \'Driver — motor driver dan sensor\',\n        \'Mekanik — rangka, motor, roda, blade\'\n    ],\n    prinsip: [\n        \'Satu modul, satu tanggung jawab\',\n        \'Kode bersih dan terdokumentasi\',\n        \'Pengujian di setiap tahap\',\n        \'Keamanan dan etika diutamakan\'\n    ]\n};\n\nconsole.log(\'Lapisan:\', ARSITEKTUR_ROBOLAB.lapisan.length);\nconsole.log(\'Prinsip:\', ARSITEKTUR_ROBOLAB.prinsip.length);',
                        '```',
                        '---',
                        '### Fitur Kunci yang Harus Ada',
                        '```javascript',
                        '// Fitur kunci RoboLab\nconst FITUR_ROBOLAB = {\n    mekanik: [\'rangka kokoh\', \'motor torsi tinggi\', \'roda grip\', \'blade efektif\'],\n    elektronik: [\'ESP32\', \'driver motor\', \'sensor ultrasonik\', \'sensor inframerah\'],\n    firmware: [\'pembacaan sensor\', \'kontrol motor\', \'WiFi server\', \'mesin state\'],\n    web: [\'antarmuka kontrol\', \'WebSocket\', \'tampilan sensor\', \'kontrol manual/otomatis\'],\n    kendali: [\'PID kecepatan\', \'AFC dorong\', \'navigasi\', \'strategi sumo\']\n};\n\nconsole.log(\'Fitur yang harus didemokan:\', Object.keys(FITUR_ROBOLAB));',
                        '```',
                        '---',
                        '### Rubrik Penilaian UAS',
                        'table:[{"No": "1", "Kriteria": "Fungsionalitas robot", "Bobot": "25%", "Deskripsi": "Robot berfungsi, semua fitur utama berjalan"}, {"No": "2", "Kriteria": "Kualitas firmware dan web", "Bobot": "25%", "Deskripsi": "Kode bersih, terstruktur, terdokumentasi"}, {"No": "3", "Kriteria": "Inovasi dan kedalaman", "Bobot": "20%", "Deskripsi": "Ada fitur tambahan atau strategi yang melampaui dasar"}, {"No": "4", "Kriteria": "Dokumentasi dan repo", "Bobot": "15%", "Deskripsi": "README, skema, panduan lengkap"}, {"No": "5", "Kriteria": "Presentasi dan demo", "Bobot": "15%", "Deskripsi": "Demo lancar, penjelasan jelas, tanya jawab memuaskan"}]',
                        '---',
                        '### Target Kualitas',
                        'skill:100%:Robot berfungsi tanpa error:Wajib',
                        'skill:95%:Firmware dan aplikasi web terintegrasi:Wajib',
                        'skill:90%:Dokumentasi lengkap dan rapi:Wajib',
                        'skill:85%:Presentasi jelas dan meyakinkan:Wajib',
                        '---',
                        '### Tips Terakhir',
                        'card:Lakukan Dry Run:Demo yang lancar adalah hasil latihan. Lakukan dry run minimal dua kali sebelum demo sesungguhnya.',
                        'card:Siapkan Fallback:Jika ada masalah teknis, siapkan rekaman demo sebagai cadangan. Jangan bergantung pada satu jalur.',
                        'card:Jawab dengan Data:Setiap pertanyaan penguji sebaiknya dijawab dengan data — angka, metrik, atau bukti kode. Hindari jawaban spekulatif.',
                        '---',
                    ],
                },
            ],
        },
    ],
};


        
